### PR TITLE
Support for Fedora using dnf package manager

### PR DESCRIPTION
**Pull request by danstiner**
I run Fedora but wanted to use this excellent role so I refactored a tad, split out platform-dependent tasks, and added an alternative implementation for the dnf package manager to install the rpm version of VSCode.

I'm no ansible expert, but I'm happy to touch this up if you have some feedback.

Verified on Fedora 25, but not yet on Ubuntu.

### CODE REVIEW

**Comment by Voronenko** [comment]
Thank you very much, I will merge & in main branch introduce :
1) add fedora to travis automated tests.
2) reflect new supported system in meta.

**Comment by Voronenko** [comment]
@danstiner Thank you very much for your input.

Your code is also suitable for CentOS-es
Updated version released to target Fedora 25, Centos6 , Centos 7
https://travis-ci.org/softasap/sa-visual-studio-code/builds/195496364

You are cool !

**Comment by danstiner** [comment]
Thanks for making this role and taking my contribution!

I didn't know you could use docker in TravisCI to test multiple distributions, that's super useful.

**Comment by Voronenko** [comment]
It's a bit abnormal approach (for example, I failed so far to introduce services with systemd for such tests so far), but generally it is better than just checking roles syntax.

If you would have more contributions you are welcome.  My goal is to have more or less robust set of roles, that setup components in a most simple way - i.e. no hundreds of role parameters. Just the most minimal necessary  patching.

I constantly use roles during my work, so they are pretty tested in production

**Comment by danstiner** [comment]
I think that is a great approach, if an opportunity comes up again to contribute I definitely will!

**Pull request merged**
